# Generated by Django 4.1 on 2022-11-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UProfile',
        ),
    ]
