# Generated by Django 4.1 on 2022-11-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Obj', max_length=100)),
                ('extension', models.CharField(default='obj', max_length=20)),
                ('model_file_size', models.IntegerField(default=0)),
                ('model_vertices', models.IntegerField(default=0)),
                ('model_height', models.IntegerField(default=0)),
                ('model_width', models.IntegerField(default=0)),
                ('model_depth', models.IntegerField(default=0)),
                ('view_profile', models.ImageField(upload_to='objs')),
                ('blob_str', models.CharField(default='', max_length=100)),
                ('tags', models.TextField(default='[]')),
                ('view_ym', models.CharField(default='', max_length=240)),
                ('view_yp', models.CharField(default='', max_length=240)),
                ('view_xp', models.CharField(default='', max_length=240)),
                ('view_xm', models.CharField(default='', max_length=240)),
                ('view_zp', models.CharField(default='', max_length=240)),
                ('view_zm', models.CharField(default='', max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dataset', max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('objects_per_image', models.IntegerField(default=5)),
                ('job_generated', models.BooleanField(default=False)),
                ('objs_list_json_str', models.TextField(default='[]')),
                ('no_images', models.IntegerField(default=10)),
                ('image_height', models.IntegerField(default=100)),
                ('image_width', models.IntegerField(default=100)),
                ('image_extension', models.CharField(choices=[('JPEG', 'JPEG')], default='JPEG', max_length=8)),
                ('color_mode', models.CharField(choices=[('RGB', 'RGB')], default='RGB', max_length=8)),
                ('json_label', models.BooleanField(default=True)),
                ('segmented_labelling', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
