# Generated by Django 4.1 on 2022-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_dataset_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obj',
            name='view_xm',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='view_xp',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='view_ym',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='view_yp',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='view_zm',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='view_zp',
        ),
    ]
